- install
This just adds a quick check for the existence of `~/.local/bin` during installation and creates it if necessary.
> [#16] Create ~/.local/bin during install if it does not exist

- install
This updates the `read_default` function in the install script to address shellcheck warnings. Namely, passing the `-r` option to `read` and double-quoting the `$dest` variable.
> [#17] Address shellcheck warnings

- hs-init.hs
I see there was already a pull request for this issue, but it appears to have some problems so I thought I would submit my own solution.
The year string was added to the ProjectData data type and as a parameter to the customizeLicense  function as it can no longer be a globally available constant.
I am fairly new to haskell, let me know if there is anything that should be improved before merge.
> [#22] Get year automatically

- CHANGELOG.md
- README.md
- appveyor.yml
- hs-init.hs
Resolves #45 
I've added AppVeyor as a separate CLI flag. Maybe if `--ci` specifed we can add both Travis and AppVeyor. I'm not sure what is more convenient for users. Maybe somebody don't want to deal with Windows...
I've also performed some cosmetic changes. And added `appveyor.yml` to `hs-init`.
@vrom911 you probably need to add `hs-init` project to AppVeyor to launch builds. I don't know how `chmod +x` works on Windows and how can I launch `hs-init --help` on Windows so I just build it with `ghc` on Windows.
Here is the example of project I've created to test AppVeyor:
* https://github.com/ChShersh/appveyor-test2
> [#45] Add AppVeyor to hs-init

- .gitignore
- CHANGELOG.md
- README.md
- hs-init.hs
- install.ps1
Crazies like me like to work on windows sometimes.  This pr introduces a few changes to help improve the windows compatibility.
- Added a powershell install script and windows install instruction to README
- Replaced unicode chatacter → in prompt as it causes problems in
standard windows terminals
- created putStrFlush to be used instead of T.putStr, ensure content is
flushed to the console and prompts are displayed in the correct order
- replaced use of "rm" with System.Directory removeFile.  Wrapped in a
function deleteFile to continue on error
- modify setScriptCommand to do nothing on windows systems
*****
These changes should provide a basic level of support for windows platforms.  There are still some outstanding issues which are not addressed by this change:
- The build script …
> Windows compatibility

- CHANGELOG.md
- src/Summoner/Template.hs
> [#92] Remove -fhide-source-paths for GHC < 8.2

- .gitignore
- .travis.yml
- CHANGELOG.md
- src/Summoner/Template.hs
Resolves #97 
Resolves #99 
Tested on [this](https://github.com/vrom911/new) project. See generated Travis file: https://github.com/vrom911/new/blob/master/.travis.yml . Note, that `cabal new-test` fails if there are no tests, so I made another check and making simple `echo` if test stanza was not chosen.
> [#97] Add travis for Cabal

- src/Summoner/CLI.hs
- src/Summoner/Config.hs
- src/Summoner/Decision.hs
- src/Summoner/Default.hs
- src/Summoner/GhcVer.hs
- src/Summoner/Project.hs
- src/Summoner/ProjectData.hs
- src/Summoner/Question.hs
- src/Summoner/Template.hs
- summoner.cabal
- test/Test/DecisionSpec.hs
- test/Test/TomlSpec.hs
This is only a step in breaking `Template` into smaller pieces. Breaking `Template` requires to introduce about 20 `newtype`s in `ProjectData` module. So I decided to move `GhcVer` and `Decision` into separate modules to not mix different things.
This PR also contains some other refactoring.
> [#125] Move Decision and GhcVer into their own modules

- summoner.cabal
Resolves #156 
This is a temporary fix. Should be reverted after migration to newer `tomland` version (see #155). Also, we should add more bounds later.
> [#156] Add build-depends constraint

- src/Summoner/Tree.hs
This fixes [#126]:  
replaced | with ├  to make the tree look like the "tree" cli tool.
Simplest fix ever :D
> modfiy tree pretty-printer arm symbol

- CHANGELOG.md
- src/Summoner/Source.hs
- summoner.cabal
- test/Test/TomlSpec.hs
this fixes #154 
but I have failing tests and I'm not sure I'm carrying it out the right way.
`cContributing` is having a bit of a nightmare but I wonder why would `Link` differ from `Url`?
> [#154] - Add Link constructor to Source data type

- CHANGELOG.md
- src/Summoner/Template.hs
- change is limited to the template for appveyor config file
- tested with a project generated with the new version of summon which builds ok in appveyor
- **tested only with GHC 8.4.3**
closes https://github.com/kowainik/summoner/issues/169
> fix: change appveyor config file to 64 bit (stack & generated binary)

- CHANGELOG.md
- src/Summoner/Template/GitHub.hs
- src/Summoner/Text.hs
Add a `tconcatMap` function, and replace
usages of `T.concat` and `map` in other places.
Resolves #189
I didn't find that many usages to be refactored, but this should be pretty useful in the future.
> [#189] Add tconcatMap to Summoner.Text

- CHANGELOG.md
- src/Summoner/CLI.hs
- src/Summoner/License.hs
- src/Summoner/Project.hs
- src/Summoner/Template/Cabal.hs
- src/Summoner/Template/Doc.hs
*  Add licenses short descriptions text during the interactive mode.
*  Patch `summon show license` command to show short description about
each license.
Resolves #199
> [#199]   Add `None` license with no `LICENSE` file generation.

- src/Summoner/Tui.hs
- src/Summoner/Tui/EditField.hs
- src/Summoner/Tui/Kit.hs
- summoner.cabal
Resolves :chicken: 
Introduces `EditField` data type.
> Introduce EditField data type

- README.md
- summoner-cli/CHANGELOG.md
- summoner-cli/src/Summoner/CLI.hs
- summoner-cli/src/Summoner/Project.hs
- summoner-tui/src/Summoner/Tui/Kit.hs
> Revert optional project name

- README.md
To successfully build `summoner-tui` via `cabal new-build all` you must have the `libtinfo` library installed. Without it the build fails with the following error because the `vty` dependency requires it (on Debian Linux, at least):
```
[21 of 36] Compiling Graphics.Vty.Input.Loop ( src/Graphics/Vty/Input/Loop.hs, dist/build/Graphics/Vty/Input/Loop.o )
<command line>: can't load .so/.DLL for: libtinfo.so (libtinfo.so: cannot open shared object file: No such file or directory)
cabal: Failed to build vty-5.25.1 (which is required by exe:summon-tui from
summoner-tui-0.0.0). See the build log above for details.
```
To summoner maintainers: feel free to tweak wording, placement in file, etc.
*Hint:* Add the `[ci skip]` text to the docs-only related commit's name, so no need …
> Note that libtinfo is needed to build summoner-tui

- summoner-cli/CHANGELOG.md
- summoner-cli/src/Summoner/Default.hs
- summoner-cli/src/Summoner/GhcVer.hs
- summoner-cli/src/Summoner/Project.hs
- summoner-cli/src/Summoner/Template/Cabal.hs
- summoner-cli/src/Summoner/Template/GitHub.hs
- summoner-cli/test/golden/fullProject/.travis.yml
It doesn't work for Stack when the version of GHC is 8.0.2 because it uses old Stack, not the one that is configured, but it shouldn't work with the old version of Cabal (manually writing `stack setup --no-terminal --install-cabal 2.2.0.1` doesn't help as well.
__UPD:__ We decided not to add old GHC into Stack Travis matrix.
Resolves #272 
Resolves #275 
> [#272] [#275] Travis improvements for generated project

- .travis.yml
- stack.yaml
- summoner-cli/CHANGELOG.md
- summoner-cli/src/Summoner/CLI.hs
- summoner-cli/src/Summoner/GhcVer.hs
- summoner-cli/src/Summoner/Settings.hs
- summoner-cli/src/Summoner/Template/GitHub.hs
- summoner-cli/src/Summoner/Template/Script.hs
- summoner-cli/summoner.cabal
- summoner-cli/test/Spec.hs
- summoner-cli/test/Test/Script.hs
- summoner-cli/test/golden/fullProject/.travis.yml
- summoner-cli/test/golden/fullProject/stack-8.4.4.yaml
- summoner-cli/test/golden/fullProject/stack.yaml
- summoner-tui/src/Summoner/Tui.hs
Resolves #285
Currently support of `script` command for TUI mode does the same as for CLI mode. I think implementing TUI for this command is separate big issue...
> [#285] Implement 'summon script' command

- appveyor.yml
- stack-8.2.2.yaml
- summoner-cli/src/Summoner/Tree.hs
- summoner-cli/summoner.cabal
- summoner-cli/test/Test/Golden.hs
- summoner-tui/summoner-tui.cabal
This PR implements better output of diff in tests when there's mismatch between golden examples and scaffolded by `summoner` project. It uses `tree-diff` library (thanks @phadej for implementing it!).
If there are errors in `fullProject` the output is big. But it's still possible and relatively convenient to find error so it can be fixed easily.
> Better golden testing using 'tree-diff'

- summoner-tui/CHANGELOG.md
- summoner-tui/src/Summoner/Tui/Kit.hs
Resolves #297
Seems that we already handle this in CLI. So this fixes TUI interface.
> [#297] Strip project description in TUI

- summoner-cli/summoner.cabal
Resolves #341
The changes implemented in `ansi-terminal-0.10` do not affect this package.
* Update CHANGELOG _Not applicable_
> [#341] Allow ansi-terminal 0.10

- appveyor.yml
AppVeyor CI fails for some weird reason. This is happening because we're using the latest `cabal` and `cabal-3.0` doesn't work (yet). Instead of figuring out, why it doesn't work, I just fixed `cabal` version to 2.4 and I also used this `appveyor.yml` script from this blog post:
* https://hub.zhox.com/posts/introducing-haskell-dev/
> Refactor AppVeyor CI config

- summoner-cli/CHANGELOG.md
- summoner-cli/src/Summoner/CLI.hs
- summoner-cli/src/Summoner/GhcVer.hs
- summoner-cli/src/Summoner/Text.hs
- summoner-tui/CHANGELOG.md
- summoner-tui/src/Summoner/Tui.hs
Resolves #314 
Been trying to align the words in the columns but getting stumped due to having to wrangle with showBulletList. Any tips? I seem to have bitten off a bit more than i can chew here haha
Currently the output looks like this: 
```
➤ 8.6.5 base-4.12.0.0 lts-13.27
➤ 8.4.4 base-4.11.1.0 lts-12.26
➤ 8.2.2 base-4.10.1.0 lts-11.22
➤ 8.0.2 base-4.9.1.0 lts-9.21 
➤ 7.10.3 base-4.8.0.2 lts-6.35 
```
> [#314] Add base and lts versions to summon show ghc output

- summoner-tui/CHANGELOG.md
- summoner-tui/src/Summoner/Tui.hs
- summoner-tui/src/Summoner/Tui/Validation.hs
Resolves #255
Demo: https://asciinema.org/a/ZBozTD81nqMUpBGnf09jhM1xr
> Autofill prelude module name when package name is typed

- cabal.project
- stack-nightly.yaml
- stack.yaml
- summoner-cli/src/Summoner/Config.hs
- summoner-cli/src/Summoner/Source.hs
- summoner-cli/summoner.cabal
- summoner-cli/test/Test/TomlSpec.hs
This is only the first part of #333. You can see how the config will look like in this PR:
* https://github.com/kowainik/org/pull/36
I've tested it locally on this config, and it works. It parses correctly :+1: When I print to terminal, I see the following:
```
Config {
...
, cFiles = fromList
[ (".github/CODEOWNERS"
, Url "https://raw.githubusercontent.com/kowainik/org/master/.github/CODEOWNERS"
)
, ( ".stylish-haskell.yaml"
, Url "https://raw.githubusercontent.com/kowainik/org/master/.stylish-haskell.yaml"
)
]
}
```
> [#333] Introduce Map field for custom files to config

- summoner-cli/CHANGELOG.md
- summoner-cli/src/Summoner/Config.hs
- summoner-cli/src/Summoner/Project.hs
- summoner-cli/test/Test/TomlSpec.hs
- summoner-tui/src/Summoner/Tui/Kit.hs
> [#374] Remove deprecated `warnings` field of the config

- summoner-cli/src/Summoner/License.hs
- summoner-cli/summoner.cabal
Resolves #382
I've tested; it still works when it works. However, I can't prove the error case, since downloading and parsing works for me. But error messages should be better now.
> [#382] Improve error logging when fetching the license from GitHub

- CHANGELOG.md
- summoner-cli/src/Summoner/Project.hs
Resolves #394
This is what user will see if `hub` is not installed:
> [#394] Warning if hub is not present

- stack.yaml
- summoner-cli/summoner.cabal
- summoner-cli/test/Spec.hs
- summoner-cli/test/Test/DecisionSpec.hs
- summoner-cli/test/Test/TomlSpec.hs
I absolutely liked [hspec-hedgehog](https://hackage.haskell.org/package/hspec-hedgehog) library and decided o try to use it. Seems like a very nice addition to our testing standards. Let me know what you think first, @chshersh !
> Use hspec-hedgehog for property tests

- README.md
This change fixes the `Examples` link of the README table of content.
> Add missing back anchor to README example

- .headroom.yaml
- headroom-templates/haskell.mustache
Hello,
as we discussed in #457, I prepared [Headroom](https://github.com/vaclavsvejcar/headroom) configuration for _Summoner_ to make integration easier for you 🙂
This PR expects that you use the up-to-date version from `master` branch, as the changes you requested to make integration with _Summoner_ are not released yet (will be part of the `0.3.0.0` major release).
Also there are two files where some manual action will be required:
1. `summoner-cli/src/Summoner/Template/GitHub.hs` - Due to the fact that the _Haddock_ module header starts with `{-|` and not `{- |` (difference in space), _Headroom_ doesn't detect this as valid license header and instead replacing it, it puts new one at the top. Changing the `{-|` to `{- |` should make it.
1. `summoner-cli/src/Summoner/Project.hs` - With …
> Add configuration for Headroom

- summoner-cli/src/Summoner.hs
- summoner-cli/src/Summoner/CLI.hs
- summoner-cli/src/Summoner/Config.hs
- summoner-cli/src/Summoner/CustomPrelude.hs
- summoner-cli/src/Summoner/Decision.hs
- summoner-cli/src/Summoner/Default.hs
- summoner-cli/src/Summoner/GhcVer.hs
- summoner-cli/src/Summoner/License.hs
- summoner-cli/src/Summoner/Mode.hs
- summoner-cli/src/Summoner/Project.hs
- summoner-cli/src/Summoner/Question.hs
- summoner-cli/src/Summoner/Settings.hs
- summoner-cli/src/Summoner/Source.hs
- summoner-cli/src/Summoner/Template.hs
- summoner-cli/src/Summoner/Template/Cabal.hs
- summoner-cli/src/Summoner/Template/Doc.hs
- summoner-cli/src/Summoner/Template/GitHub.hs
- summoner-cli/src/Summoner/Template/Haskell.hs
- summoner-cli/src/Summoner/Template/Script.hs
- summoner-cli/src/Summoner/Template/Stack.hs
- summoner-cli/src/Summoner/Text.hs
- summoner-cli/src/Summoner/Tree.hs
- summoner-tui/src/Summoner/Tui.hs
- summoner-tui/src/Summoner/Tui/Field.hs
- summoner-tui/src/Summoner/Tui/Form.hs
- summoner-tui/src/Summoner/Tui/GroupBorder.hs
- summoner-tui/src/Summoner/Tui/Kit.hs
- summoner-tui/src/Summoner/Tui/Validation.hs
- summoner-tui/src/Summoner/Tui/Widget.hs
Using [headroom](https://github.com/vaclavsvejcar/headroom) to manage headers automatically. I've performed the following steps:
1. Run `headroom init -l mpl2 -s summoner-cli/src/`
2. Manually edit `headroom` files
3. Run `headroom run -v "author=Kowainik" -v "year=2020"`
It's a nice tool :slightly_smiling_face: But there are a few things that stop us from using `headroom` in all our projects. Maybe my configuration is wrong in some places, so I would appreciate any tips.
1. Currently `headroom` doesn't replace the top-level module documentation, it always adds a new entry (even when `replace` mode is enabled)
2. It doesn't substitute `LONG_DESC` and `MODULE_NAME` variables.
3. It doesn't preserve existing years (since it doesn't replace the header) and doesn't update years automatically …
> Use headroom to prettify headers

- summoner-cli/examples/cabal-full/README.md
- summoner-cli/examples/full-batteries/README.md
- summoner-cli/examples/stack-full/README.md
- summoner-cli/src/Summoner/Template/Doc.hs
New repos are no longer available on <https://travis-ci.org>,
but only on <https://travis-ci.com>.
See also: https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
Closes: #449
> Point Travis CI badge to travis-ci.com/<repo_name>

- stack.yaml
- summoner-cli/summoner.cabal
I bumped the version, confirmed that the code builds and the tests pass. I did some smoke testing of the CLI (`--version`, `--help` with and without subcmd, `new`). I was able to confirm that the bump really changes something - it fixes pcapriotti/optparse-applicative#379 .
Fixes #499
> [#499] Bump `optparse-applicative` to use 0.16

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- summoner-cli/examples/cabal-full/.github/workflows/ci.yml
- summoner-cli/examples/cabal-full/.travis.yml
- summoner-cli/examples/cabal-full/appveyor.yml
- summoner-cli/examples/cabal-full/cabal-full.cabal
- summoner-cli/examples/cabal-minimal/cabal-minimal.cabal
- summoner-cli/examples/full-batteries/.github/workflows/ci.yml
- summoner-cli/examples/full-batteries/.travis.yml
- summoner-cli/examples/full-batteries/appveyor.yml
- summoner-cli/examples/full-batteries/full-batteries.cabal
- summoner-cli/examples/stack-full/.github/workflows/ci.yml
- summoner-cli/examples/stack-full/.travis.yml
- summoner-cli/examples/stack-full/appveyor.yml
- summoner-cli/examples/stack-full/stack-full.cabal
- summoner-cli/src/Summoner/Default.hs
- summoner-cli/src/Summoner/Template/GitHub.hs
- summoner-cli/summoner.cabal
- summoner-tui/summoner-tui.cabal
> [#340] Move to cabal-3.0
