kowainik/summoner

hs-init.hs
install

These changes update the install script to prompt for defaults for owner, name, and email address.

[#17] Prompt for default settings

---

CHANGELOG.md
README.md
hs-init.hs

@ChShersh could you please review when you have time just to be sure I'm not doing strange things in the project?
Resolves #36

[#36] Option -p/--private

---

CHANGELOG.md
README.md
hs-init.hs

Update lts version. Set default `ghc` to `8.2.2`.

Bump to lts-10.3

---

hs-init.hs

I have tested current settings for test projects. Build passes. But I had an issue with having `cabal >=2.0`. `setup --upgrade-cabal` failed with strange error on `8.0.2`..

[#3] Improve Travis config, refactor

---

.travis.yml
CONTRIBUTING.md
LICENSE
README.md
hs-init.hs
install
install.ps1

Travis integration added.
Also I fixed links and default values :wink:

Fix travis, fix links, rename all to kowainik

---

CHANGELOG.md
README.md
src/Summoner/CLI.hs

[#54] Rename on/off to with/without

---

.stylish-haskell.yaml
src/Summoner/CLI.hs
src/Summoner/Default.hs
src/Summoner/Project.hs
src/Summoner/ProjectData.hs
src/Summoner/Question.hs
src/Summoner/Template.hs
summoner.cabal

[#50] Introduce data type for GHC version

---

src/Summoner/Project.hs
summoner.cabal
test/Spec.hs
test/Test/DecisionSpec.hs

Resolves #53 
Maybe there're some more tests we need to add. Just tell me and I can add them.

[#53] Add property-based tests for semigroup/monoid laws

---

CHANGELOG.md
README.md
src/Summoner.hs
src/Summoner/Ansi.hs
src/Summoner/CLI.hs
src/Summoner/Config.hs
src/Summoner/Default.hs
src/Summoner/Project.hs
src/Summoner/ProjectData.hs
src/Summoner/Question.hs
src/Summoner/Template.hs
src/Summoner/Validation.hs
stack.yaml
summoner.cabal
test/Test/DecisionSpec.hs

[#48] Add configurations, read from the file

---

CHANGELOG.md
src/Prelude.hs
src/Summoner/Ansi.hs
src/Summoner/CLI.hs
src/Summoner/Config.hs
src/Summoner/Default.hs
src/Summoner/License.hs
src/Summoner/Process.hs
src/Summoner/Project.hs
src/Summoner/ProjectData.hs
src/Summoner/Question.hs
src/Summoner/Template.hs
src/Summoner/Validation.hs
stack.yaml
summoner.cabal
test/Test/DecisionSpec.hs

[#60] Use universum as default prelude

---

CHANGELOG.md
README.md
app/Main.hs
src/Summoner/CLI.hs
src/Summoner/Config.hs
src/Summoner/Project.hs
src/Summoner/ProjectData.hs
src/Summoner/Template.hs

Resolves #39 
Note: #65  should be done for this one to work correctly (the reason is `stack.yaml` creation).

[#39] Add option for custom prelude

---

CHANGELOG.md
README.md
src/Summoner/Config.hs
src/Summoner/Project.hs
src/Summoner/ProjectData.hs
src/Summoner/Template.hs

[#38] Add option for default extensions in config

---

src/Summoner/Project.hs
src/Summoner/Template.hs
src/Summoner/Tree.hs
summoner.cabal

Resolves #65 
It's also much faster than `stack new`. And almost allows us to have offline mode.

[#65] Replace 'stack new' with our tree traversal

---

CHANGELOG.md
README.md
src/Summoner/Ansi.hs
src/Summoner/CLI.hs
src/Summoner/Default.hs
src/Summoner/Project.hs
src/Summoner/Template.hs

Resolves #62 
Also, I did some refactoring regarding minor polishing.

[#62] Print bold text

---

CHANGELOG.md
src/Summoner/Project.hs
src/Summoner/ProjectData.hs
src/Summoner/Question.hs

[#67] Add Answer data type

---

CHANGELOG.md
README.md
src/Summoner/CLI.hs
summoner.cabal

[#61] Add --version option

---

CHANGELOG.md
README.md
src/Summoner/CLI.hs
src/Summoner/Config.hs
src/Summoner/Project.hs
src/Summoner/Template.hs
stack.yaml

Resolves #73 
Need to release `tomland-0.2.1` first. Currently prelude parsing doesn't work as expected.

[#73] Write parser for CustomPrelude as table in toml

---

.travis.yml
stack-8.4.2.yaml

Resolves #77 
This PR need to be updated after #75 is merged to `master`.

[#77] Build with GHC-8.4.2 on CI

---

CHANGELOG.md
src/Summoner/Project.hs
src/Summoner/Tree.hs

[#74] Add showTree function

---

README.md
src/Summoner/Template.hs
summoner.cabal

[#80] Add demo

---

CHANGELOG.md
app/Main.hs
src/Prelude.hs
src/Summoner/Ansi.hs
src/Summoner/CLI.hs
src/Summoner/Config.hs
src/Summoner/Default.hs
src/Summoner/License.hs
src/Summoner/Process.hs
src/Summoner/Project.hs
src/Summoner/ProjectData.hs
src/Summoner/Question.hs
src/Summoner/Template.hs
src/Summoner/Text.hs
src/Summoner/Tree.hs
src/Summoner/Validation.hs
stack-8.4.2.yaml
stack.yaml
summoner.cabal
test/Test/DecisionSpec.hs

[#85] Remove base-noprelude dependency

---

CHANGELOG.md
src/Summoner/Template.hs
summoner.cabal

[#87] Fix travis matrix

---

.travis.yml
CHANGELOG.md
README.md
src/Summoner/Config.hs
stack-8.4.2.yaml
stack-8.4.3.yaml
stack.yaml
summoner.cabal

Changes version of `tomland` to `0.3` and adds upper-bound to it.
I've tested it on our `.summoner.toml` config, it works.

Bump up to tomland-0.3

---

CHANGELOG.md
README.md
app/Main.hs
src/Summoner/Ansi.hs
src/Summoner/CLI.hs
src/Summoner/Config.hs
src/Summoner/Default.hs
src/Summoner/License.hs
src/Summoner/Process.hs
src/Summoner/Project.hs
src/Summoner/ProjectData.hs
src/Summoner/Question.hs
src/Summoner/Template.hs
src/Summoner/Text.hs
src/Summoner/Tree.hs
src/Summoner/Validation.hs
stack-8.2.2.yaml
stack.yaml
summoner.cabal
test/Test/DecisionSpec.hs

Use relude as prelude

---

CHANGELOG.md
README.md
src/Summoner/CLI.hs
src/Summoner/ProjectData.hs
stack.yaml

[#105] Add --ignore-config option

---

src/Summoner/Template.hs

[#82] Add stackage badges

---

.travis.yml
CHANGELOG.md
src/Summoner/Template.hs

Resolves [#109](https://github.com/kowainik/summoner/issues/109)

[#109] Fix travis cache

---

src/Summoner/Template.hs

Resolves [#109](https://github.com/kowainik/summoner/issues/109)
Bug revealed after merged.

[109] Fix hot

---

CHANGELOG.md
src/Summoner/Process.hs

Resolves [#110](https://github.com/kowainik/summoner/issues/110)

[#110] Print executing command

---

CHANGELOG.md
src/Summoner/Project.hs

[#117] Step into created project properly

---

CHANGELOG.md
README.md
src/Summoner/Config.hs
src/Summoner/ProjectData.hs
src/Summoner/Template.hs
summoner.cabal
test/Test/DecisionSpec.hs
test/Test/TomlSpec.hs

Resolves [#90](https://github.com/kowainik/summoner/issues/90)

[#90] Add TOML test

---

CHANGELOG.md
src/Summoner/Config.hs
src/Summoner/License.hs
src/Summoner/Project.hs
src/Summoner/ProjectData.hs
src/Summoner/Question.hs
src/Summoner/Template.hs
test/Test/TomlSpec.hs

Resolves [#58](https://github.com/kowainik/summoner/issues/58)

[#58] Make License type safer

---

CHANGELOG.md
src/Summoner/Question.hs
src/Summoner/Tree.hs
summoner.cabal

Resolves [#124](https://github.com/kowainik/summoner/issues/124)

[#124] Print directories bold

---

CHANGELOG.md
README.md
src/Summoner/CLI.hs
summoner.cabal

[#128] Make summon new command

---

CHANGELOG.md
src/Summoner/Ansi.hs
src/Summoner/CLI.hs
src/Summoner/Tree.hs
summoner.cabal

Resolves [#130](https://github.com/kowainik/summoner/issues/130)

[#130] Show git revision

---

CHANGELOG.md
README.md
src/Summoner/CLI.hs
src/Summoner/Config.hs
src/Summoner/License.hs
src/Summoner/Project.hs
src/Summoner/ProjectData.hs
src/Summoner/Question.hs
src/Summoner/Template.hs
summoner.cabal

Resolves [#63](https://github.com/kowainik/summoner/issues/63)

[#63] Add show commands

---

CHANGELOG.md
src/Summoner/Template.hs

Resolves [#122](https://github.com/kowainik/summoner/issues/122)

[#122] Fix changelog and readme

---

CHANGELOG.md
README.md
src/Summoner/Config.hs
src/Summoner/Project.hs
src/Summoner/ProjectData.hs
src/Summoner/Source.hs
src/Summoner/Template.hs
stack-8.2.2.yaml
stack.yaml
summoner.cabal
test/Test/TomlSpec.hs

 [#35] Add config option to add stylish file

---

CHANGELOG.md
README.md
src/Summoner/Config.hs
src/Summoner/Project.hs
src/Summoner/ProjectData.hs
src/Summoner/Template.hs
test/Test/TomlSpec.hs

[#31] Add generation of CONTRIBUTING.md file

---

README.md
src/Summoner/CLI.hs
src/Summoner/Config.hs
src/Summoner/Project.hs
src/Summoner/ProjectData.hs
src/Summoner/Template.hs
test/Test/TomlSpec.hs

Resolves #27 
Improve README
Improve benchmarks cabal section
Remove 'module Main where' in executable

[#27] Remove b-script support

---

.travis.yml
CHANGELOG.md
app/Main.hs
src/Prelude.hs
src/Summoner/Ansi.hs
src/Summoner/CLI.hs
src/Summoner/Config.hs
src/Summoner/Decision.hs
src/Summoner/Default.hs
src/Summoner/GhcVer.hs
src/Summoner/License.hs
src/Summoner/Process.hs
src/Summoner/Project.hs
src/Summoner/ProjectData.hs
src/Summoner/Question.hs
src/Summoner/Source.hs
src/Summoner/Template.hs
src/Summoner/Text.hs
src/Summoner/Tree.hs
src/Summoner/Validation.hs
stack-8.2.2.yaml
stack.yaml
summoner.cabal
test/Test/DecisionSpec.hs
test/Test/TomlSpec.hs

[#146] Migrate to base-noprelude (and bump up relude)

---

.travis.yml

Added `.hlint.yaml` that ignores any HLint errors up to this point

Add HLint check to Travis CI

---

src/Summoner/Project.hs
src/Summoner/Template/Doc.hs
src/Summoner/Template/Haskell.hs

Clean up some code with Maybes

---

CHANGELOG.md
src/Summoner/GhcVer.hs
src/Summoner/Template/Cabal.hs
src/Summoner/Template/Doc.hs
src/Summoner/Template/GitHub.hs
src/Summoner/Template/Haskell.hs
src/Summoner/Template/Stack.hs

Resolves #178
Also resolves #168

[#178] Remove trailing spaces, newlines

---

src/Summoner/Project.hs
src/Summoner/Settings.hs
src/Summoner/Template/Cabal.hs
src/Summoner/Template/Doc.hs
src/Summoner/Template/GitHub.hs

Resolves #180 
I hope that I filled out the checklist correctly. Otherwise, let me know :)

Rename settingsBase, -Vey, -Github to -BaseType, -Veyor, -GitHub

---

CHANGELOG.md
src/Summoner/GhcVer.hs
src/Summoner/Template/Cabal.hs

[#142] Add base bounds to the generated cabal file

---

.travis.yml
CHANGELOG.md
src/Summoner/Config.hs
src/Summoner/GhcVer.hs
src/Summoner/Settings.hs
src/Summoner/Source.hs
stack-8.2.2.yaml
stack-8.6.1.yaml
stack-8.6.2.yaml
stack.yaml
summoner.cabal

[#155] Migrate to tomland-0.5.0

---

CHANGELOG.md
src/Summoner.hs
summoner.cabal
test/Spec.hs
test/Test/DecisionSpec.hs
test/Test/Golden.hs
test/Test/QuestionSpec.hs
test/Test/TomlSpec.hs
test/golden/fullProject/.gitignore
test/golden/fullProject/.stylish-haskell.yaml
test/golden/fullProject/.travis.yml
test/golden/fullProject/CHANGELOG.md
test/golden/fullProject/CONTRIBUTING.md
test/golden/fullProject/LICENSE
test/golden/fullProject/README.md
test/golden/fullProject/app/Main.hs
test/golden/fullProject/appveyor.yml
test/golden/fullProject/benchmark/Main.hs
test/golden/fullProject/fullProject.cabal
test/golden/fullProject/src/FullProject.hs
test/golden/fullProject/src/Prelude.hs
test/golden/fullProject/stack-8.0.2.yaml
test/golden/fullProject/stack-8.2.2.yaml
test/golden/fullProject/stack.yaml
test/golden/fullProject/test/Spec.hs
test/golden/smallProject/CHANGELOG.md
test/golden/smallProject/README.md
test/golden/smallProject/app/Main.hs
test/golden/smallProject/smallProject.cabal

[#185] Add golden tests

---

CHANGELOG.md
README.md
src/Summoner/CLI.hs
src/Summoner/Project.hs
src/Summoner/Source.hs

[#11] Support offline mode

---

src/Summoner/Tui.hs
src/Summoner/Tui/Kit.hs

Resolves 🔨 
Horizontal alignment to be added  later (it's too complicated 😞)

[#208] Add tools section

---

src/Summoner/Tui.hs
src/Summoner/Tui/EditField.hs
src/Summoner/Tui/Kit.hs

Add user form

---

src/Summoner/Tui.hs

Small improvement to the help message.

[#208] Better help form

---

src/Summoner/Tui.hs
src/Summoner/Tui/Kit.hs

Add validation for Cabal or Stack
Add validation for Lib or Exe
Add parsing of GHC versions
Resolves 🍇

[#208] Add Project Meta section

---

src/Summoner/Tui.hs
src/Summoner/Tui/Forms.hs
summoner.cabal

🔥 🚒 🔥 🚒 🔥 
Ctr+d now deletes the whole input in owner field.
Changed colours just to play
Ctrl+Enter doesn't work
Resolves 💢

Add textField for Forms

---

src/Summoner/Tui.hs
src/Summoner/Tui/Forms.hs

Resolves :rage1: 
Required to copy-paste the implementation of `customCheckboxField` and refactor it.

[#208] Make checkboxes disableable

---

src/Summoner/Tui.hs

Resolves :church: 
Error messages are very simple for now. In ideal case it's better to report what exactly wrong with field (and probably introduce fancier error message) but should be good for now. At least it works.

[#208] Add basic on-the-fly error reporting

---

src/Summoner/Tui.hs

Resolves :building_construction: 
Currently it reads all  directories at the beginning. But I guess this is an okay approximation.

[#208] Implement validation for project existence

---

src/Summoner/Tui.hs
src/Summoner/Tui/Kit.hs

Add basic structured tree widget

---

src/Summoner/Project.hs
src/Summoner/Tree.hs
src/Summoner/Tui.hs
src/Summoner/Tui/Kit.hs
src/Summoner/Tui/Widget.hs
summoner.cabal

Do not make directories in tree bold
Rearrange help and error widgets
Add Widget helper module
Resolves ⚰️

[#208] Make tools section horizontal

---

app/Cli.hs
src/Summoner/CLI.hs
src/Summoner/License.hs
src/Summoner/Tui.hs
src/Summoner/Tui/Widget.hs

Add CLI to summon-tui

---

src/Summoner/Tui.hs
src/Summoner/Tui/Field.hs
src/Summoner/Tui/Form.hs
src/Summoner/Tui/Validation.hs
summoner.cabal

Move out Form and Validation logic

---

src/Summoner/Tui.hs
src/Summoner/Tui/Form.hs
src/Summoner/Tui/Kit.hs
src/Summoner/Tui/Validation.hs
src/Summoner/Tui/Widget.hs
stack-8.2.2.yaml
stack-8.6.2.yaml
stack.yaml
summoner.cabal

Resolves 👪 
* Migrate to `brick-0.41.4`.
* Use `setFormFocus` on <kbd>Ctrl</kbd> + <kbd>d</kbd>
* Add pretty padding for border labels
* Add `noUpload` button
* Use `gitHubEnabled` field in `Settings`

Various TUI improvements

---

src/Summoner/CLI.hs
src/Summoner/Tui.hs
src/Summoner/Tui/Kit.hs

[#208] Fill SummonKit by the config and CLI

---

src/Summoner/Tui.hs
src/Summoner/Tui/Form.hs

Preserve focus on creating new form

---

src/Summoner/CLI.hs
src/Summoner/Project.hs
src/Summoner/Settings.hs
src/Summoner/Tui.hs
src/Summoner/Tui/Kit.hs
test/Test/Golden.hs

[#208] Create the project via TUI interface

---

src/Summoner/Tui.hs
src/Summoner/Tui/Field.hs
src/Summoner/Tui/Form.hs

Customize checkboxes and colors for edit fields

---

src/Summoner/Tui.hs
src/Summoner/Tui/Field.hs
src/Summoner/Tui/Form.hs
src/Summoner/Tui/GroupBorder.hs
src/Summoner/Tui/Kit.hs

[#208] Refactor TUI module, add more docs

---

src/Summoner/Tui.hs
src/Summoner/Tui/GroupBorder.hs
src/Summoner/Tui/Validation.hs

[#208] Improve Help

---

summoner-tui/src/Summoner/Tui.hs
summoner-tui/src/Summoner/Tui/Kit.hs

[#208] Add confirm window on Enter

---

summoner-tui/src/Summoner/Tui.hs
summoner-tui/src/Summoner/Tui/Field.hs
summoner-tui/src/Summoner/Tui/Form.hs
summoner-tui/src/Summoner/Tui/Validation.hs

Resolves :heavy_check_mark: 
* Handles `Space` on activatable checkboxes
* Skips deactivated checkboxes when using `Tab/BackTab`

[#208] Handle checkboxes better

---

README.md
summoner-cli/CHANGELOG.md
summoner-cli/src/Summoner/CLI.hs
summoner-cli/src/Summoner/Project.hs
summoner-cli/src/Summoner/Question.hs
summoner-tui/src/Summoner/Tui/Kit.hs

[#243] Make project name optional in cli arguments

---

summoner-tui/src/Summoner/Tui.hs

Add info to some form fields, add Info coloring

---

summoner-cli/src/Summoner/CLI.hs
summoner-tui/src/Summoner/Tui.hs
summoner-tui/src/Summoner/Tui/Kit.hs

Resolves :information_source:
I also did some refactoring.

Display whether config was used

---

README.md
appveyor.yml

[#256] Add Appveyor CI

---

.github/pull_request_template.md

[#257] Update PR template, simplify

---

.travis.yml

Resolves only part of #159, specifically:
* Creates release for Linux
* Creates release for OSX
Have no idea whether it works. I've tried to compile knowledge from multiple resources...

[#159] Try to configure Linus/OSX deploys

---

summoner-cli/CHANGELOG.md
summoner-cli/src/Summoner/Template/Cabal.hs
summoner-cli/src/Summoner/Template/GitHub.hs
summoner-cli/test/golden/fullProject/.travis.yml

[#37] Add HLint check to Travis of the generated project

---

.travis.yml
appveyor.yml

Resolves :desktop_computer: 
If CI passes, I guess this can be merged to `master` to be checked later.

Add Windows deploys from AppVeyor CI

---

summoner-cli/src/Summoner/GhcVer.hs
summoner-cli/test/golden/fullProject/stack.yaml
summoner-tui/src/Summoner/Tui.hs

Improve TUI colours, use lts 12.20

---

README.md
summoner-cli/CHANGELOG.md
summoner-tui/CHANGELOG.md

Update installation instructions and changelog

---

summoner-cli/summoner.cabal

[#270] Add golden tests to data-dir

---

summoner-cli/CHANGELOG.md
summoner-cli/src/Summoner/Project.hs

[#268] Simplify adding custom prelude in CLI

---

.travis.yml

Implements `summoner` part of the issues #275 and #272. The same improvements for the generated projects still remain.

[#275] [#272] New simple travis settings

---

.travis.yml
stack.yaml

Attempts to make `.travis.yml` even more simpler and efficient.

[#272] Simplify Travis for summoner even more

---

stack-8.2.2.yaml
stack-8.4.4.yaml
stack.yaml
summoner-cli/CHANGELOG.md
summoner-cli/src/Summoner/Config.hs
summoner-cli/src/Summoner/Source.hs
summoner-cli/summoner.cabal

[#286] Bump up to tomland-1.0.0

---

README.md

Resolves #167
As discussed with @pascalpoizat we decided to add this info so that anyone facing these issues can reuse this information.
Thank you very much @pascalpoizat for providing this information and links!

[#167] Add FAQ section with remote change info

---

stack-8.2.2.yaml
stack-8.4.4.yaml
stack.yaml
summoner-cli/src/Summoner/Process.hs
summoner-cli/src/Summoner/Project.hs
summoner-cli/summoner.cabal

[#288] Use shellmet library

---

summoner-cli/CHANGELOG.md
summoner-cli/src/Summoner/Project.hs
summoner-cli/src/Summoner/Template/GitHub.hs
summoner-cli/test/golden/fullProject/appveyor.yml
summoner-tui/CHANGELOG.md
summoner-tui/src/Summoner/Tui/Form.hs

Resolves #280
Seems working. See test repo here:
* https://github.com/ChShersh/summon-appvey-test

[#280] Support appveyor for cabal

---

README.md
stack-8.2.2.yaml
stack-8.4.4.yaml
stack.yaml
summoner-cli/CHANGELOG.md
summoner-cli/src/Summoner/CLI.hs
summoner-cli/summoner.cabal

[#261] Try to guess user name and email from .gitconfig

---

.travis.yml
appveyor.yml
stack-8.2.2.yaml
stack-8.4.4.yaml
stack.yaml
summoner-cli/CHANGELOG.md
summoner-cli/src/Summoner/Template/GitHub.hs
summoner-cli/summoner.cabal
summoner-cli/test/golden/fullProject/appveyor.yml
summoner-tui/src/Summoner/Tui.hs
summoner-tui/summoner-tui.cabal

[#304] Bump up to relude-0.5.0 and brick-0.47

---

README.md
summoner-cli/CHANGELOG.md
summoner-cli/src/Summoner/CLI.hs
summoner-cli/src/Summoner/Config.hs
summoner-cli/src/Summoner/Project.hs
summoner-cli/test/Test/TomlSpec.hs
summoner-tui/src/Summoner/Tui.hs
summoner-tui/src/Summoner/Tui/Kit.hs

[#303] Add noUpload option to toml config

---

.travis.yml
README.md
summoner-cli/CHANGELOG.md
summoner-cli/src/Summoner/Template/Cabal.hs
summoner-cli/src/Summoner/Template/Doc.hs
summoner-cli/summoner.cabal
summoner-cli/test/golden/fullProject/CHANGELOG.md
summoner-cli/test/golden/fullProject/README.md
summoner-cli/test/golden/fullProject/fullProject.cabal
summoner-cli/test/golden/smallProject/CHANGELOG.md
summoner-cli/test/golden/smallProject/README.md
summoner-cli/test/golden/smallProject/smallProject.cabal
summoner-tui/summoner-tui.cabal

[#316] Add logo to badges, small improvements

---

summoner-cli/summoner.cabal

[#320] Allow bump-up hedgehog to 1.0

---

.travis.yml
appveyor.yml
summoner-cli/summoner.cabal

Resolves #323
Seems like we can just ake a revision at Hackage

[#323] Allow tree-diff-0.1

---

.travis.yml
cabal.project
summoner-cli/CHANGELOG.md
summoner-cli/src/Summoner/Template/GitHub.hs
summoner-cli/test/golden/fullProject/.travis.yml

[#322] Run HLint check before build

---

stack.yaml
summoner-cli/CHANGELOG.md
summoner-cli/summoner.cabal

[#328] Upgrade to tomland-1.1.0.0

---

.travis.yml
README.md
stack.yaml
summoner-cli/CHANGELOG.md
summoner-cli/src/Summoner/GhcVer.hs
summoner-cli/src/Summoner/Template/Cabal.hs
summoner-cli/src/Summoner/Template/Doc.hs
summoner-cli/summoner.cabal
summoner-cli/test/Test/Script.hs
summoner-cli/test/golden/fullProject/.travis.yml
summoner-cli/test/golden/fullProject/README.md
summoner-cli/test/golden/fullProject/fullProject.cabal
summoner-cli/test/golden/fullProject/stack.yaml
summoner-cli/test/golden/smallProject/smallProject.cabal
summoner-tui/summoner-tui.cabal

[#318] Support 8.6.5, use 8.6.5

---

.gitignore
.travis.yml
README.md
default.nix

Resolves #150
I still need to fix an issue with README/LICENSE symlink as indicated #334. Once that's done this PR will be ready to be merged. But first, I'd like know if this PR is welcome.

Add support for building summoner using Nix

---

summoner-cli/src/Summoner/Text.hs
summoner-tui/CHANGELOG.md
summoner-tui/src/Summoner/Tui/Validation.hs

Part of #354 
Demo: https://asciinema.org/a/G5uCtFcVIzfNdUeSX7TvHdGe4

Validate prelude package name in TUI

---

.gitignore
.travis.yml
stack-nightly.yaml
stack.yaml
summoner-cli/CHANGELOG.md
summoner-cli/src/Summoner/Config.hs
summoner-cli/src/Summoner/CustomPrelude.hs
summoner-cli/src/Summoner/Decision.hs
summoner-cli/src/Summoner/GhcVer.hs
summoner-cli/src/Summoner/License.hs
summoner-cli/src/Summoner/Question.hs
summoner-cli/src/Summoner/Settings.hs
summoner-cli/src/Summoner/Source.hs
summoner-cli/src/Summoner/Tree.hs
summoner-cli/summoner.cabal
summoner-tui/CHANGELOG.md
summoner-tui/src/Summoner/Tui/Form.hs
summoner-tui/src/Summoner/Tui/Kit.hs
summoner-tui/summoner-tui.cabal

[#338] Build summoner with GHC-8.8

---

README.md

Partially addresses #159.
Hi Kowainik team,
I've made `summoner` installable via the Scarf package manager and added instructions to the readme. Happy to either transfer package ownership fully or co-maintain it. Thanks!
- [] [summoner-cli/CHANGELOG](https://github.com/kowainik/summoner/blob/master/summoner-cli/CHANGELOG.md).
- [] [summoner-tui/CHANGELOG](https://github.com/kowainik/summoner/blob/master/summoner-tui/CHANGELOG.md).
- [] Keep code style used in the changed files (see [style-guide](https://github.com/kowainik/org/blob/master/style-guide.md#haskell-style-guide) for more details).
- [] Use the [`stylish-haskell` file](https://github.com/kowainik/summoner/blob/master/.stylish-haskell.yaml).
- [] Create a new test project using `summoner` and check that the …

[#159] Scarf install instructions

---

summoner-tui/CHANGELOG.md
summoner-tui/src/Summoner/Tui/Validation.hs

Validate module name in TUI

---

summoner-cli/src/Summoner/Project.hs
summoner-cli/src/Summoner/Question.hs

[#354] Validate package and module names in CLI

---

summoner-cli/src/Summoner.hs
summoner-cli/src/Summoner/Process.hs
summoner-cli/src/Summoner/Project.hs
summoner-cli/src/Summoner/Settings.hs
summoner-cli/src/Summoner/Shell.hs
summoner-cli/summoner.cabal
summoner-cli/test/Test/Golden.hs
summoner-tui/src/Summoner/Tui.hs
summoner-tui/src/Summoner/Tui/Kit.hs

Next part of #333 
I tested it locally, files are actually created!

Create specified extra files

---

summoner-cli/src/Summoner/Project.hs
summoner-tui/src/Summoner/Tui.hs

Part of #333
Here is how it looks in TUI:
I've tested in both CLI and TUI and it seems to work :+1: If you have better ideas regarding text or how to write code, let me know...

Add deprecation messages

---

README.md
summoner-cli/src/Summoner/Default.hs

[#315] Add docs on using newer build tools versions

---

.travis.yml
cabal.project
stack-nightly.yaml
stack.yaml
summoner-cli/CHANGELOG.md
summoner-cli/src/Summoner/Config.hs
summoner-tui/CHANGELOG.md

[#373] Use tomland-1.2.1.0

---

appveyor.yml
summoner-cli/CHANGELOG.md
summoner-cli/src/Summoner/Template/GitHub.hs
summoner-cli/test/golden/fullProject/appveyor.yml

Resolves #327
I've tested `stack`-only AppVeyor on this project, it passes:
* https://github.com/chshersh/test-stack-appveyor
And the `cabal` AppVeyor is the same as for `summoner`, so it's already tested.

[#327] Improve Appveyor config

---

.travis.yml

[#384] Test that generated projects are build on CI

---

summoner-cli/CHANGELOG.md
summoner-cli/src/Summoner/CLI.hs
summoner-cli/src/Summoner/GhcVer.hs
summoner-cli/src/Summoner/Text.hs
summoner-cli/summoner.cabal
summoner-cli/test/Spec.hs
summoner-cli/test/Test/Show.hs
summoner-tui/src/Summoner/Tui.hs

[#385] Tests for `show` commands

---

CHANGELOG.md
README.md
summoner-cli/src/Summoner/CLI.hs
summoner-cli/src/Summoner/Template/Doc.hs
summoner-cli/test/golden/fullProject/README.md
summoner-tui/src/Summoner/Tui.hs
summoner-tui/src/Summoner/Tui/Form.hs
summoner-tui/src/Summoner/Tui/Kit.hs

[#395] Add TUI button for GitHub Actions

---

summoner-cli/src/Summoner/Template/GitHub.hs
summoner-cli/src/Summoner/Template/Haskell.hs
summoner-cli/test/golden/fullProject/.github/workflows/ci.yml
summoner-cli/test/golden/fullProject/test/Spec.hs

It should be 'CI', so the badge image could work

Fix GitHub Avtions name

---

cabal.project
stack-nightly.yaml
stack.yaml
summoner-cli/src/Summoner/Ansi.hs
summoner-cli/src/Summoner/CLI.hs
summoner-cli/src/Summoner/Project.hs
summoner-cli/src/Summoner/Question.hs
summoner-cli/src/Summoner/Source.hs
summoner-cli/src/Summoner/Tree.hs
summoner-cli/summoner.cabal

Code became simpler in many places, but I wasn't able to remove the `Summoner.Ansi` module completely...

Migrate to colourista

---

CHANGELOG.md
stack.yaml
summoner-cli/src/Summoner/Config.hs
summoner-cli/src/Summoner/Decision.hs
summoner-cli/summoner.cabal

Resolves #363
That was quite painless :slightly_smiling_face:

[#363] Use `generic-data` instead of `generic-deriving`

---

CHANGELOG.md
README.md
summoner-cli/src/Summoner/Default.hs
summoner-cli/src/Summoner/Template/Cabal.hs
summoner-cli/test/golden/fullProject/fullProject.cabal
summoner-cli/test/golden/smallProject/smallProject.cabal

[#246] Put common parts of the project inside `common` stanza

---

CHANGELOG.md
summoner-cli/src/Summoner/License.hs

[#251] cabal 2.2 changes names of BSD licenses

---

.github/workflows/ci.yml
README.md
cabal.project
summoner-cli/src/Summoner/Template/GitHub.hs

[#398] Improve GitHub Actions CI cache support

---

CHANGELOG.md
summoner-cli/src/Summoner/Template/Cabal.hs
summoner-cli/src/Summoner/Template/Haskell.hs
summoner-cli/test/golden/fullProject/fullProject.cabal
summoner-cli/test/golden/fullProject/src/FullProject.hs
summoner-cli/test/golden/fullProject/test/Spec.hs
summoner-cli/test/golden/smallProject/app/Main.hs
summoner-cli/test/golden/smallProject/smallProject.cabal

[#399] Add Haddock header to library module

---

CHANGELOG.md
README.md
summoner-cli/src/Summoner/Config.hs
summoner-cli/src/Summoner/Project.hs
summoner-cli/src/Summoner/Settings.hs
summoner-cli/src/Summoner/Source.hs
summoner-cli/src/Summoner/Template/Doc.hs
summoner-cli/src/Summoner/Template/Haskell.hs
summoner-cli/test/Test/Golden.hs
summoner-tui/src/Summoner/Tui.hs
summoner-tui/src/Summoner/Tui/Kit.hs

[#375] Remove deprecated `stylish` and `contributing` fields of the config

---

CHANGELOG.md
summoner-cli/src/Summoner/Project.hs

[#34] Github password.

---

CHANGELOG.md
summoner-cli/src/Summoner/Template/GitHub.hs
summoner-cli/test/golden/fullProject/.github/workflows/ci.yml
summoner-cli/test/golden/fullProject/.travis.yml

[#418] Make cabal-2.4 default

---

.github/workflows/ci.yml
.travis.yml
appveyor.yml

This PR is an attempt to bring better binary GitHub releases to `summoner`.

Better GitHub releases

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
stack.yaml
summoner-cli/examples/cabal-full/.github/workflows/ci.yml
summoner-cli/examples/cabal-full/.travis.yml
summoner-cli/examples/cabal-full/appveyor.yml
summoner-cli/examples/cabal-full/cabal-full.cabal
summoner-cli/examples/cabal-minimal/cabal-minimal.cabal
summoner-cli/examples/full-batteries/.github/workflows/ci.yml
summoner-cli/examples/full-batteries/.travis.yml
summoner-cli/examples/full-batteries/appveyor.yml
summoner-cli/examples/full-batteries/full-batteries.cabal
summoner-cli/examples/full-batteries/stack.yaml
summoner-cli/examples/stack-full/.travis.yml
summoner-cli/examples/stack-full/stack-full.cabal
summoner-cli/examples/stack-full/stack.yaml
summoner-cli/examples/summoner-default.toml
summoner-cli/src/Summoner/GhcVer.hs
summoner-cli/summoner.cabal
summoner-cli/test/Test/Show.hs
summoner-tui/summoner-tui.cabal

[#429] Move to GHC-8.8.3

---

CHANGELOG.md
README.md
stack.yaml
summoner-cli/examples/cabal-full/.travis.yml
summoner-cli/examples/full-batteries/.travis.yml
summoner-cli/examples/full-batteries/stack.yaml
summoner-cli/examples/stack-full/.travis.yml
summoner-cli/examples/stack-full/stack.yaml
summoner-cli/src/Summoner/GhcVer.hs
summoner-cli/src/Summoner/Project.hs
summoner-cli/src/Summoner/Template/GitHub.hs
summoner-cli/test/Test/Show.hs

[#430] Allow-failures for old GHC on Stack at TravisCI

---

.github/workflows/ci.yml
.travis.yml
summoner-cli/summoner.cabal
summoner-tui/summoner-tui.cabal

[#436] Remove GHC-8.2.2 check from the CI

---

CHANGELOG.md
stack.yaml
summoner-cli/src/Summoner/CLI.hs
summoner-cli/src/Summoner/Config.hs
summoner-cli/summoner.cabal
summoner-cli/test/Test/TomlSpec.hs
summoner-tui/src/Summoner/Tui/Validation.hs
summoner-tui/summoner-tui.cabal

[#434] Move to 'validation-selective'

---

summoner-cli/summoner.cabal

[#433] Add missing files to extra-source-files

---

README.md

Add installation instructions for Mac and Ubuntu

---

README.md

[#423] Rerecord demo videos

---

.github/workflows/ci.yml
CHANGELOG.md
summoner-cli/summoner.cabal
summoner-tui/summoner-tui.cabal

Resolves #443
I found two unused packages. It didn't warn me before, not sure why :disappointed:

[#443] Test Summoner with GHC-8.10

---

.github/workflows/ci.yml
summoner-cli/summoner.cabal

[#467] Allow aeson-1.5.0.0

---

CHANGELOG.md
summoner-cli/summoner.cabal
summoner-tui/summoner-tui.cabal

[#469] Brick-0.54

---

.github/workflows/ci.yml
CHANGELOG.md
summoner-cli/examples/cabal-full/.github/workflows/ci.yml
summoner-cli/examples/cabal-full/.travis.yml
summoner-cli/examples/full-batteries/.github/workflows/ci.yml
summoner-cli/examples/full-batteries/.travis.yml
summoner-cli/src/Summoner/Template/GitHub.hs

[#466] Add `--test-dhow-details=direct` to CI tests

---

CHANGELOG.md
stack.yaml
summoner-cli/src/Summoner/Config.hs
summoner-cli/src/Summoner/License.hs
summoner-cli/summoner.cabal

[#476] Swap aeson with microaeson

---

CHANGELOG.md
summoner-cli/examples/cabal-full/cabal-full.cabal
summoner-cli/examples/cabal-minimal/cabal-minimal.cabal
summoner-cli/examples/full-batteries/full-batteries.cabal
summoner-cli/examples/stack-full/stack-full.cabal
summoner-cli/src/Summoner/Template/Cabal.hs

[#446] Add link to README in cabal description link

---

.gitignore
CHANGELOG.md
README.md
summoner-cli/examples/cabal-full/.gitignore
summoner-cli/examples/cabal-full/cabal-full.cabal
summoner-cli/examples/cabal-minimal/cabal-minimal.cabal
summoner-cli/examples/full-batteries/.gitignore
summoner-cli/examples/stack-full/.gitignore
summoner-cli/examples/stack-full/stack-full.cabal
summoner-cli/src/Summoner/Template/Cabal.hs
summoner-cli/src/Summoner/Template/GitHub.hs
summoner-cli/summoner.cabal
summoner-tui/summoner-tui.cabal

[#482] Add GHC options to generate the HIE files

---

summoner-cli/src/Summoner/CLI.hs
summoner-cli/src/Summoner/GhcVer.hs
summoner-cli/src/Summoner/Tree.hs
summoner-cli/summoner.cabal
summoner-cli/test/Test/TomlSpec.hs
summoner-tui/src/Summoner/Tui.hs
summoner-tui/src/Summoner/Tui/Form.hs
summoner-tui/src/Summoner/Tui/Validation.hs

Resolves #496
There were 30 observations, now down to 2 (`length` ones which are not resolvable now).
The code was actually pretty good already 👍🏼

[#496] Run Stan on Summoner and fix observations

---

.travis.yml
summoner-cli/examples/cabal-full/.travis.yml
summoner-cli/examples/full-batteries/.travis.yml
summoner-cli/examples/stack-full/.travis.yml
summoner-cli/src/Summoner/Template/GitHub.hs

*  remove deprecated `sudo` key
*  replace matrix with jobs
Fixes #504 .

Update travis.yaml template

---

summoner-tui/summoner-tui.cabal

Allow brick 0.56

---

summoner-tui/summoner-tui.cabal

Allow brick 0.57 and vty 5.31

---

README.md
summoner-cli/examples/cabal-full/cabal-full.cabal
summoner-cli/examples/cabal-minimal/cabal-minimal.cabal
summoner-cli/examples/stack-full/stack-full.cabal
summoner-cli/src/Summoner/Template/Cabal.hs
summoner-cli/summoner.cabal
summoner-tui/summoner-tui.cabal

[#448] Add -Wnoncanonical-monad-instances

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
appveyor.yml
summoner-cli/examples/cabal-full/.github/workflows/ci.yml
summoner-cli/examples/cabal-full/README.md
summoner-cli/examples/cabal-full/appveyor.yml
summoner-cli/examples/full-batteries/.github/workflows/ci.yml
summoner-cli/examples/full-batteries/README.md
summoner-cli/examples/full-batteries/appveyor.yml
summoner-cli/examples/stack-full/.github/workflows/ci.yml
summoner-cli/examples/stack-full/README.md
summoner-cli/examples/stack-full/appveyor.yml
summoner-cli/examples/summoner-default.toml
summoner-cli/src/Summoner/Default.hs
summoner-cli/src/Summoner/Project.hs
summoner-cli/src/Summoner/Template/Doc.hs
summoner-cli/src/Summoner/Template/GitHub.hs

[#517] Create projects with main branch

---

stack.yaml
summoner-cli/src/Summoner/CLI.hs
summoner-cli/src/Summoner/GhcVer.hs
summoner-cli/src/Summoner/License.hs
summoner-cli/src/Summoner/Project.hs
summoner-cli/src/Summoner/Question.hs
summoner-cli/src/Summoner/Settings.hs
summoner-cli/summoner.cabal
summoner-cli/test/Test/TomlSpec.hs
summoner-tui/src/Summoner/Tui.hs
summoner-tui/src/Summoner/Tui/Form.hs
summoner-tui/src/Summoner/Tui/Validation.hs
summoner-tui/summoner-tui.cabal

Using the latest feature of `reexported-modules` in action

Migrate to relude 1.0

---

CHANGELOG.md
summoner-cli/src/Summoner/Project.hs

[#520] Output link to the repo in the terminal in the end

---

CHANGELOG.md
summoner-cli/examples/cabal-full/.github/dependabot.yml
summoner-cli/examples/full-batteries/.github/dependabot.yml
summoner-cli/examples/stack-full/.github/dependabot.yml
summoner-cli/src/Summoner/Template/GitHub.hs

[#495] Add dependabot.yml with GitHub Actions

---

cabal.project
stack.yaml
summoner-cli/summoner.cabal
summoner-tui/src/Summoner/Tui/Field.hs
summoner-tui/summoner-tui.cabal

[#561] Use microaeson from hackage instead of the fork

---

.github/CODEOWNERS
.github/workflows/ci.yml
CHANGELOG.md
stack.yaml
summoner-cli/summoner.cabal
summoner-tui/src/Summoner/Tui.hs
summoner-tui/src/Summoner/Tui/Field.hs
summoner-tui/src/Summoner/Tui/Widget.hs
summoner-tui/summoner-tui.cabal

[#565] Support GHC-9.2, use brick-1.0
